### ISSUE TITLE
DefaultState used upon init

### ISSUE THREAD

**Issue by gensior** [kawan16/mithril-ui-router#1]
Not sure what to title this issue, but I'll explain the situation using your mithril-ui-router app as an example.

If I go to the [about page](http://kawan16.github.io/mithril-ui-router/#/about]) from an outside link or a page refresh, mithril-ui-router's behavior redirects to the [home page](http://kawan16.github.io/mithril-ui-router/#/home), even though there's a route for `/about`.

I think the correct behavior should be to go to `/about` and ignore the defaultState since it maps to an existing route.

I hope that makes sense.

**Comment by kawan16** [comment]
Hi Jesse, 

That makes perfect sense. I really believed I pushed this feature a couple of days ago but I didn't. So, I fixed it in the demo and of course in the source / dist folders.

Now when you are in the about page ( or others ) and refresh, you will stay in this page.

**Comment by gensior** [comment]
Thanks! Your router makes a lot of sense to me and I'm using it while trying to learn mithril as a whole. I used angular-ui-router before and I'm glad you've got this out there. Keep up the good work.
