### ISSUE TITLE
Mithril ui router broken when using mithril 0.2.0

### ISSUE THREAD

**Issue by aarontropy** [kawan16/mithril-ui-router#3]
The [example page](http://kawan16.github.io/mithril-ui-router/#/home) at http://kawan16.github.io/mithril-ui-router/#/home works fine with Mithril version 0.1.34, but change mithril to version 0.2.0 and sub states (like home.contact, etc) do not render.

**Comment by kawan16** [comment]
Indeed, the router was compliant with the lastest 0.1.34 version not the 0.2. Apparently, the module function does not have the same functional coverage. I upgrade the router and the demo to be 0.2 compliant. I will release the 0.12 of the router soon.
