### ISSUE TITLE
Rendering components in state module views not working

### ISSUE THREAD

**Issue by aarontropy** [kawan16/mithril-ui-router#4]
If the view of a state module renders a component ie:

``` javascript
app.mod = {
    view: function() { return m.component(myComponent); }
}
```

then, when the state changes (eg when you call mx.route.go), the component won't render.  This is not the case when the browser navigates to the state.

For example, navigating to a state that tries to render a component will succeed, but the component won't render.  After hitting refresh on that page, the component appears.

Example app:

``` javascript
var myComponent = {
  view: function() {
    return m("div", {style: "background: #1ABC9C"}, "This is my component");
  }
};

function fakeComponent() {
  return m("div", {style: "background: #F39C12"}, "This is a faked component");
}


function stateLink(name, state) {
  return m('a[href=""]',
    {
      onclick: function(evt) {
        evt.preventDefault();
        mx.route.go(state);
      },
    },
    m("li", name));
}

var layout = {
  view: function() {
    return [
      m("ul", [
        stateLink("With Component", "base.state1"),
        stateLink("Without Component", "base.state2"),
      ]),
      m("div", {style: "border-bottom: 1px solid black"}, "Current state output"),
      m("div#state-container"),
    ];
  },
};

var state1 = {
  view: function() {
    return m.component(myComponent);
  }
};

var state2 = {
  view: function() {
    return fakeComponent();
  }
};

var app = {
  layout: layout,
  state1: state1,
  state2: state2,
};

mx.route(app, 'base.state1', {
  'base': {
    url: '',
    module: 'layout',
    place: '#app',
  },
  'base.state1': {
    url: '/state1',
    module: 'state1',
    place: '#state-container',
  },
  'base.state2': {
    url: '/state2',
    module: 'state2',
    place: '#state-container',
  },
});
```

**Comment by aarontropy** [comment]
This has something to do with the number of pendingRequests.  The component gets replaced with a `<placeholder>` tag at line 249 of mithril.js.  The difference between rendering after a refresh and after a state change is the number if pendingRequests (0 for browser refresh, 1 for state change).

**Comment by aarontropy** [comment]
After a little reading, it appears this is not a mithril-ui-router problem, but a known issue in mithril: lhorie/mithril.js#682

The workaround proposed in that thread is to use `setTimeout()` to call `render()` asynchronously so that the click event handled by mithril can complete.  

It is easier to change the example app code above than to wrap larger portions of ui-router in `setTimeout()`, so I made the following change to my example code:

``` javascript
function stateLink(name, state) {
  return m('a[href=""]',
    {
      onclick: function(evt) {
        evt.preventDefault();
        setTimeout(function() {
            mx.route.go(state);
        },0);
      },
    },
    m("li", name));
}
```

With that change, the example works as expected.

**Comment by kawan16** [comment]
Hi Aaron, 

I'm happy to hear it's out of the router and there's a workaround for that. I will pay attention if this mithril  issue will be fixed soon or if I have to put  the setTimeout directly in some way in the go function ! 

Thanks for your feedback !

**Comment by mismith** [comment]
I'm still experiencing this bug; any idea if it has been fixed or if a more thorough workaround now exists?
